# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026 Invariant Systems, Inc.
"""
Tests for aiir._release_bundle — portable release evidence bundle.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
import unittest
from collections import OrderedDict
from pathlib import Path

from aiir._core import _canonical_json, _sha256, CLI_VERSION
from aiir._release_bundle import (
    BUNDLE_SCHEMA,
    BUNDLE_FORMAT_VERSION,
    build_bundle_manifest,
    build_release_bundle,
    collect_receipt_artifacts,
    format_bundle_summary,
    render_auditor_report_html,
    write_release_bundle,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _pad_sha(sha: str) -> str:
    return sha.ljust(40, "0") if len(sha) < 40 else sha


def _make_receipt(
    sha: str = "abc123",
    ai: bool = False,
    authorship: str = "human",
    signed: bool = False,
) -> dict:
    padded_sha = _pad_sha(sha)
    core = {
        "type": "aiir.commit_receipt",
        "schema": "aiir/commit_receipt.v1",
        "version": CLI_VERSION,
        "commit": {
            "sha": padded_sha,
            "author": {
                "name": "Test",
                "email": "test@example.com",
                "date": "2026-03-09T12:00:00Z",
            },
            "committer": {
                "name": "Test",
                "email": "test@example.com",
                "date": "2026-03-09T12:00:00Z",
            },
            "subject": "test commit",
            "message_hash": "sha256:" + "a" * 64,
            "diff_hash": "sha256:" + "b" * 64,
            "files_changed": 1,
            "files": ["test.py"],
        },
        "ai_attestation": {
            "is_ai_authored": ai,
            "is_bot_authored": False,
            "authorship_class": authorship,
            "detection_method": "heuristic_v2",
            "signals_detected": ["Generated by Copilot"] if ai else [],
            "signal_count": 1 if ai else 0,
        },
        "provenance": {
            "repository": "https://github.com/test/repo",
            "ref": "main",
            "tool": "https://github.com/invariant-systems-ai/aiir@v" + CLI_VERSION,
            "generator": "aiir/" + CLI_VERSION,
        },
    }
    core_json = _canonical_json(core)
    receipt = {
        **core,
        "content_hash": "sha256:" + _sha256(core_json),
        "receipt_id": "g1-" + _sha256(core_json)[:32],
        "timestamp": "2026-03-09T12:00:00Z",
        "extensions": {},
    }
    if signed:
        receipt["extensions"]["sigstore_bundle"] = "mock_bundle_ref"
    return receipt


def _write_ledger(dir_path: Path, receipts: list) -> str:
    ledger_path = dir_path / "receipts.jsonl"
    ledger_path.write_text(
        "\n".join(_canonical_json(r) for r in receipts) + "\n", encoding="utf-8"
    )
    return str(ledger_path)


def _write_receipt_dir(base_dir: Path, receipts: list) -> str:
    receipt_dir = base_dir / "rdir"
    receipt_dir.mkdir(exist_ok=True)
    for i, r in enumerate(receipts):
        (receipt_dir / f"receipt_{i:04d}.json").write_text(
            json.dumps(r, indent=2), encoding="utf-8"
        )
    return str(receipt_dir)


# ---------------------------------------------------------------------------
# build_release_bundle — happy paths
# ---------------------------------------------------------------------------


class TestBuildReleaseBundleLedger(unittest.TestCase):
    def test_ledger_passed_bundle_structure(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(
                base, [_make_receipt("aaa"), _make_receipt("bbb", ai=True)]
            )
            bundle = build_release_bundle(
                receipts_path=ledger,
                policy_preset="balanced",
                release_name="v1.0.0",
                subject_name="git+https://example.com/repo@deadbeef",
                created_at="2026-06-06T00:00:00Z",
            )
            files = bundle["files"]
            self.assertEqual(bundle["verification_result"], "PASSED")
            self.assertEqual(bundle["result_code"], 0)
            # Required artifacts present.
            for name in (
                "manifest.json",
                "manifest.sha256",
                "verify-release.json",
                "vsa.intoto.json",
                "policy.json",
                "evidence-stream.json",
                "evidence-summary.json",
                "auditor-report.html",
                "verifier-instructions.md",
                "README.md",
            ):
                self.assertIn(name, files, name)
            # Two receipts re-serialized under receipts/.
            receipt_files = [k for k in files if k.startswith("receipts/")]
            self.assertEqual(len(receipt_files), 2)

    def test_manifest_anchor_fields(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa")])
            bundle = build_release_bundle(
                receipts_path=ledger,
                policy_preset="balanced",
                created_at="2026-06-06T00:00:00Z",
            )
            manifest = bundle["manifest"]
            self.assertEqual(manifest["schema"], BUNDLE_SCHEMA)
            self.assertEqual(manifest["bundle_format_version"], BUNDLE_FORMAT_VERSION)
            self.assertEqual(manifest["created_at"], "2026-06-06T00:00:00Z")
            self.assertEqual(manifest["aiir_version"], CLI_VERSION)
            self.assertTrue(manifest["boundary"]["declared_ai_provenance_only"])
            self.assertFalse(manifest["boundary"]["hidden_ai_detection"])
            # Every artifact has a sha256 that matches the file bytes.
            for entry in manifest["artifacts"]:
                content = bundle["files"][entry["path"]]
                self.assertEqual(entry["sha256"], hashlib.sha256(content).hexdigest())

    def test_subject_derived_from_vsa_when_not_supplied(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa")])
            bundle = build_release_bundle(
                receipts_path=ledger,
                policy_preset="balanced",
            )
            # No subject_name passed; manifest subject still populated from VSA.
            self.assertIn("subject", bundle["manifest"]["release"])

    def test_default_release_name_is_head(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa")])
            bundle = build_release_bundle(
                receipts_path=ledger, policy_preset="balanced"
            )
            self.assertEqual(bundle["manifest"]["release"]["name"], "HEAD")

    def test_emit_report_false_omits_html(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa")])
            bundle = build_release_bundle(
                receipts_path=ledger, policy_preset="balanced", emit_report=False
            )
            self.assertNotIn("auditor-report.html", bundle["files"])

    def test_failed_bundle_still_built(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            # Unsigned AI receipt under strict policy => FAILED.
            ledger = _write_ledger(base, [_make_receipt("aaa", ai=True)])
            bundle = build_release_bundle(receipts_path=ledger, policy_preset="strict")
            self.assertEqual(bundle["verification_result"], "FAILED")
            self.assertEqual(bundle["result_code"], 1)
            self.assertIn("manifest.json", bundle["files"])

    def test_empty_ledger_no_receipts_found(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = base / "receipts.jsonl"
            ledger.write_text("", encoding="utf-8")
            bundle = build_release_bundle(
                receipts_path=str(ledger), policy_preset="balanced"
            )
            self.assertEqual(bundle["verification_result"], "FAILED")
            self.assertEqual(bundle["reason"], "No receipts found")

    def test_redact_files_marks_manifest_and_report(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa", ai=True)])
            bundle = build_release_bundle(
                receipts_path=ledger,
                policy_preset="balanced",
                redact_files=True,
                redact_emails=True,
            )
            self.assertTrue(bundle["manifest"]["redactions"]["files"])
            self.assertTrue(bundle["manifest"]["redactions"]["emails"])
            html = bundle["files"]["auditor-report.html"].decode("utf-8")
            self.assertIn("redacted", html.lower())


class TestBuildReleaseBundleDir(unittest.TestCase):
    def test_dir_copies_receipts_and_sidecars(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            rdir = Path(_write_receipt_dir(base, [_make_receipt("aaa", signed=True)]))
            # Add a sigstore sidecar and a cbor sidecar for the receipt.
            receipt_json = sorted(rdir.glob("*.json"))[0]
            Path(str(receipt_json) + ".sigstore").write_text("{}", encoding="utf-8")
            receipt_json.with_suffix(".cbor").write_bytes(b"\xa0")
            bundle = build_release_bundle(
                receipts_path=str(rdir), policy_preset="balanced"
            )
            files = bundle["files"]
            self.assertTrue(any(k.startswith("signatures/") for k in files))
            self.assertTrue(any(k.endswith(".cbor") for k in files))
            # Original receipt bytes copied verbatim.
            self.assertEqual(
                files[f"receipts/{receipt_json.name}"], receipt_json.read_bytes()
            )

    def test_policy_path_explicit_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa")])
            policy_file = base / "custom-policy.json"
            policy_file.write_text(
                json.dumps({"enforcement": "warn", "require_signing": False}),
                encoding="utf-8",
            )
            bundle = build_release_bundle(
                receipts_path=ledger, policy_path=str(policy_file)
            )
            policy = json.loads(bundle["files"]["policy.json"])
            self.assertEqual(policy["enforcement"], "warn")

    def test_policy_path_missing_raises(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa")])
            # verify_release() validates the policy path first and raises.
            with self.assertRaises(FileNotFoundError):
                build_release_bundle(
                    receipts_path=ledger, policy_path=str(base / "missing.json")
                )

    def test_default_policy_when_none(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa")])
            cwd = os.getcwd()
            try:
                os.chdir(tmp)
                bundle = build_release_bundle(receipts_path=ledger)
            finally:
                os.chdir(cwd)
            self.assertIn("policy.json", bundle["files"])


# ---------------------------------------------------------------------------
# collect_receipt_artifacts
# ---------------------------------------------------------------------------


class TestCollectReceiptArtifacts(unittest.TestCase):
    def test_dir_skips_symlinked_receipt(self):
        if not hasattr(os, "symlink"):  # pragma: no cover - platform guard
            self.skipTest("symlinks unsupported")
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            rdir = base / "rdir"
            rdir.mkdir()
            real = rdir / "real.json"
            real.write_text(json.dumps(_make_receipt("aaa")), encoding="utf-8")
            link = rdir / "link.json"
            try:
                os.symlink(real, link)
            except OSError:  # pragma: no cover - platform guard
                self.skipTest("symlink creation failed")
            artifacts = collect_receipt_artifacts(str(rdir), [])
            names = [a[0] for a in artifacts]
            self.assertIn("receipts/real.json", names)
            self.assertNotIn("receipts/link.json", names)

    def test_dir_skips_symlinked_sidecars(self):
        if not hasattr(os, "symlink"):  # pragma: no cover - platform guard
            self.skipTest("symlinks unsupported")
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            rdir = base / "rdir"
            rdir.mkdir()
            real = rdir / "r.json"
            real.write_text(json.dumps(_make_receipt("aaa")), encoding="utf-8")
            # Symlinked sidecars must be skipped.
            target = base / "outside.sig"
            target.write_text("{}", encoding="utf-8")
            try:
                os.symlink(target, Path(str(real) + ".sigstore"))
                os.symlink(target, real.with_suffix(".cbor"))
            except OSError:  # pragma: no cover - platform guard
                self.skipTest("symlink creation failed")
            artifacts = collect_receipt_artifacts(str(rdir), [])
            self.assertFalse(any(a[0].startswith("signatures/") for a in artifacts))
            self.assertFalse(any(a[0].endswith(".cbor") for a in artifacts))

    def test_jsonl_uses_receipt_id_when_no_sha(self):
        receipt = _make_receipt("aaa")
        del receipt["commit"]["sha"]
        receipt["receipt_id"] = "weird/id*name"
        artifacts = collect_receipt_artifacts("not-a-dir.jsonl", [receipt])
        self.assertEqual(len(artifacts), 1)
        relpath = artifacts[0][0]
        # Unsafe characters stripped from the on-disk name.
        self.assertNotIn("/", relpath.split("receipts/")[1])
        self.assertNotIn("*", relpath)

    def test_jsonl_non_dict_commit(self):
        receipt = _make_receipt("aaa")
        receipt["commit"] = "not-a-dict"
        receipt["receipt_id"] = ""
        artifacts = collect_receipt_artifacts("ledger.jsonl", [receipt])
        self.assertTrue(artifacts[0][0].endswith("receipt.json"))


# ---------------------------------------------------------------------------
# build_bundle_manifest
# ---------------------------------------------------------------------------


class TestBuildBundleManifest(unittest.TestCase):
    def test_unknown_role_defaults_to_artifact(self):
        files: "OrderedDict[str, bytes]" = OrderedDict()
        files["x.bin"] = b"data"
        manifest = build_bundle_manifest(
            files=files,
            roles={},  # no role mapping
            release_name="v1",
            commit_range=None,
            subject="s",
            verification_result="PASSED",
            reason="ok",
            policy_digest="deadbeef",
            redactions={},
            created_at="2026-06-06T00:00:00Z",
        )
        self.assertEqual(manifest["artifacts"][0]["role"], "artifact")
        self.assertEqual(manifest["release"]["commit_range"], "")


# ---------------------------------------------------------------------------
# render_auditor_report_html — defensive branches
# ---------------------------------------------------------------------------


def _minimal_manifest() -> dict:
    return {
        "release": {"name": "v1", "commit_range": "", "subject": "s"},
        "created_at": "2026-06-06T00:00:00Z",
        "aiir_version": CLI_VERSION,
        "policy": {"digest": {"sha256": "abc"}},
    }


class TestRenderAuditorReport(unittest.TestCase):
    def test_pass_report_renders(self):
        html = render_auditor_report_html(
            manifest=_minimal_manifest(),
            verify_result={
                "verificationResult": "PASSED",
                "reason": "All checks passed",
                "coverage": {"coverage_percent": 100.0, "commits_total": 1},
                "predicate": {"evaluation": {"invalidReceipts": 0}},
                "policy_violations": [],
            },
            policy={"preset": "balanced", "enforcement": "soft-fail"},
            evidence_summary={
                "total_receipts": 1,
                "ai_receipts": 1,
                "evidence_tiers": {"signed": 1},
                "unsigned_risk": {"ai_receipts_without_signing": 0},
                "release_proof_readiness": {"ready_ratio": 100.0},
                "top_ai_systems": [{"system": "Copilot", "count": 1}],
                "hot_path_ai_changes": [{"path": "a.py", "count": 1}],
            },
            redactions={"files": False},
        )
        self.assertIn("PASSED", html)
        self.assertIn("Copilot", html)
        self.assertIn("a.py", html)
        self.assertIn("not</em> prove", html)

    def test_fail_report_with_violations(self):
        html = render_auditor_report_html(
            manifest=_minimal_manifest(),
            verify_result={
                "verificationResult": "FAILED",
                "reason": "policy violations",
                "coverage": {"coverage_percent": 50.0, "receipts_missing": ["a"]},
                "predicate": {"evaluation": {"policyViolations": 1}},
                "policy_violations": [
                    {"commit_sha": "abc123", "rule": "require_signing", "message": "x"},
                    "not-a-dict",
                ],
            },
            policy={"max_ai_percent": 50.0, "require_signing": True},
            evidence_summary={},
            redactions={"files": True},
        )
        self.assertIn("FAILED", html)
        self.assertIn("require_signing", html)
        self.assertIn("redacted", html.lower())

    def test_defensive_non_dict_fields(self):
        html = render_auditor_report_html(
            manifest=_minimal_manifest(),
            verify_result={
                "verificationResult": "UNKNOWN",
                "coverage": "not-a-dict",
                "predicate": "not-a-dict",
                "policy_violations": "not-a-list",
            },
            policy={},
            evidence_summary={
                "evidence_tiers": "x",
                "unsigned_risk": "x",
                "release_proof_readiness": "x",
                "top_ai_systems": "x",
                "hot_path_ai_changes": "x",
            },
            redactions={"files": False},
        )
        self.assertIn("UNKNOWN", html)

    def test_predicate_non_dict_evaluation(self):
        html = render_auditor_report_html(
            manifest=_minimal_manifest(),
            verify_result={
                "verificationResult": "PASSED",
                "coverage": {},
                "predicate": {"evaluation": "not-a-dict"},
                "policy_violations": [],
            },
            policy={"max_ai_percent": None},
            evidence_summary={},
            redactions={},
        )
        self.assertIn("PASSED", html)


# ---------------------------------------------------------------------------
# write_release_bundle — security + behavior
# ---------------------------------------------------------------------------


class TestWriteReleaseBundle(unittest.TestCase):
    def _simple_bundle(self) -> dict:
        files: "OrderedDict[str, bytes]" = OrderedDict()
        files["manifest.json"] = b"{}"
        files["receipts/a.json"] = b"{}"
        return {"files": files, "manifest": {"artifacts": []}}

    def test_writes_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "bundle"
            path = write_release_bundle(self._simple_bundle(), str(out))
            self.assertTrue((Path(path) / "manifest.json").is_file())
            self.assertTrue((Path(path) / "receipts" / "a.json").is_file())

    def test_str_content_is_encoded(self):
        files: "OrderedDict[str, object]" = OrderedDict()
        files["note.txt"] = "hello"  # str, not bytes
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "bundle"
            write_release_bundle({"files": files}, str(out))
            self.assertEqual((out / "note.txt").read_text(), "hello")

    def test_empty_files_raises(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(ValueError):
                write_release_bundle({"files": {}}, str(Path(tmp) / "x"))

    def test_non_empty_dir_without_overwrite_raises(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "bundle"
            out.mkdir()
            (out / "existing.txt").write_text("x")
            with self.assertRaises(ValueError):
                write_release_bundle(self._simple_bundle(), str(out))

    def test_overwrite_allows_non_empty_dir(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "bundle"
            out.mkdir()
            (out / "existing.txt").write_text("x")
            path = write_release_bundle(self._simple_bundle(), str(out), overwrite=True)
            self.assertTrue((Path(path) / "manifest.json").is_file())

    def test_output_is_symlink_raises(self):
        if not hasattr(os, "symlink"):  # pragma: no cover - platform guard
            self.skipTest("symlinks unsupported")
        with tempfile.TemporaryDirectory() as tmp:
            real = Path(tmp) / "real"
            real.mkdir()
            link = Path(tmp) / "link"
            try:
                os.symlink(real, link)
            except OSError:  # pragma: no cover - platform guard
                self.skipTest("symlink creation failed")
            with self.assertRaises(ValueError):
                write_release_bundle(self._simple_bundle(), str(link))

    def test_output_exists_as_file_raises(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "afile"
            out.write_text("x")
            with self.assertRaises(ValueError):
                write_release_bundle(self._simple_bundle(), str(out))

    def test_refuses_write_through_symlinked_parent(self):
        if not hasattr(os, "symlink"):  # pragma: no cover - platform guard
            self.skipTest("symlinks unsupported")
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "bundle"
            out.mkdir()
            outside = Path(tmp) / "outside"
            outside.mkdir()
            try:
                os.symlink(outside, out / "receipts")
            except OSError:  # pragma: no cover - platform guard
                self.skipTest("symlink creation failed")
            files: "OrderedDict[str, bytes]" = OrderedDict()
            files["receipts/a.json"] = b"{}"
            with self.assertRaises(ValueError):
                write_release_bundle({"files": files}, str(out), overwrite=True)


# ---------------------------------------------------------------------------
# format_bundle_summary
# ---------------------------------------------------------------------------


class TestFormatBundleSummary(unittest.TestCase):
    def test_summary_contains_key_fields(self):
        bundle = {
            "manifest": {
                "verification": {"result": "PASSED", "reason": "ok"},
                "artifacts": [{"path": "manifest.json"}],
            }
        }
        summary = format_bundle_summary(bundle, "/tmp/out")
        self.assertIn("PASSED", summary)
        self.assertIn("/tmp/out", summary)
        self.assertIn("auditor-report.html", summary)


# ---------------------------------------------------------------------------
# End-to-end: build then write then re-verify integrity
# ---------------------------------------------------------------------------


class TestRoundTripIntegrity(unittest.TestCase):
    def test_written_bundle_artifacts_match_manifest(self):
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ledger = _write_ledger(base, [_make_receipt("aaa"), _make_receipt("bbb")])
            bundle = build_release_bundle(
                receipts_path=ledger, policy_preset="balanced"
            )
            out = base / "evidence"
            write_release_bundle(bundle, str(out))
            manifest = json.loads((out / "manifest.json").read_text())
            for entry in manifest["artifacts"]:
                data = (out / entry["path"]).read_bytes()
                self.assertEqual(
                    hashlib.sha256(data).hexdigest(), entry["sha256"], entry["path"]
                )
            # manifest.sha256 matches manifest.json bytes.
            sha_line = (out / "manifest.sha256").read_text().split()[0]
            self.assertEqual(
                sha_line,
                hashlib.sha256((out / "manifest.json").read_bytes()).hexdigest(),
            )


# ---------------------------------------------------------------------------
# CLI: --release-bundle
# ---------------------------------------------------------------------------


class TestCLIReleaseBundle(unittest.TestCase):
    def _ledger(self, base: Path, receipts: list) -> str:
        return _write_ledger(base, receipts)

    def test_cli_builds_bundle_passed(self):
        import aiir.cli as cli

        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            ledger = self._ledger(base, [_make_receipt("a1"), _make_receipt("a2")])
            old = os.getcwd()
            try:
                os.chdir(td)
                rc = cli.main(
                    [
                        "--release-bundle",
                        "out/evidence",
                        "--receipts",
                        ledger,
                        "--policy",
                        "balanced",
                    ]
                )
                self.assertEqual(rc, 0)
                self.assertTrue(Path("out/evidence/manifest.json").is_file())
                self.assertTrue(Path("out/evidence/auditor-report.html").is_file())
            finally:
                os.chdir(old)

    def test_cli_no_emit_report_and_custom_policy_file(self):
        import aiir.cli as cli

        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            ledger = self._ledger(base, [_make_receipt("a1")])
            policy_file = base / "p.json"
            policy_file.write_text(
                json.dumps({"enforcement": "warn"}), encoding="utf-8"
            )
            old = os.getcwd()
            try:
                os.chdir(td)
                rc = cli.main(
                    [
                        "--release-bundle",
                        "out/ev",
                        "--receipts",
                        ledger,
                        "--policy",
                        str(policy_file),
                        "--no-emit-report",
                    ]
                )
                self.assertEqual(rc, 0)
                self.assertFalse(Path("out/ev/auditor-report.html").exists())
            finally:
                os.chdir(old)

    def test_cli_failed_bundle_returns_1_but_writes(self):
        import aiir.cli as cli

        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            ledger = self._ledger(base, [_make_receipt("a1", ai=True)])
            old = os.getcwd()
            try:
                os.chdir(td)
                rc = cli.main(
                    [
                        "--release-bundle",
                        "out/ev",
                        "--receipts",
                        ledger,
                        "--policy",
                        "strict",
                    ]
                )
                self.assertEqual(rc, 1)
                self.assertTrue(Path("out/ev/manifest.json").is_file())
            finally:
                os.chdir(old)

    def test_cli_default_policy_no_flag(self):
        import aiir.cli as cli

        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            ledger = self._ledger(base, [_make_receipt("a1")])
            old = os.getcwd()
            try:
                os.chdir(td)
                # No --policy flag => default policy branch.
                rc = cli.main(
                    [
                        "--release-bundle",
                        "out/ev",
                        "--receipts",
                        ledger,
                    ]
                )
                self.assertEqual(rc, 0)
            finally:
                os.chdir(old)

    def test_cli_build_error_returns_1(self):
        import aiir.cli as cli

        with tempfile.TemporaryDirectory() as td:
            old = os.getcwd()
            try:
                os.chdir(td)
                # Missing receipts path => build_release_bundle raises =>
                # handled, returns 1.
                rc = cli.main(
                    [
                        "--release-bundle",
                        "out/ev",
                        "--receipts",
                        str(Path(td) / "nope.jsonl"),
                        "--policy",
                        "balanced",
                    ]
                )
                self.assertEqual(rc, 1)
            finally:
                os.chdir(old)

    def test_cli_write_error_returns_1(self):
        import aiir.cli as cli

        with tempfile.TemporaryDirectory() as td:
            base = Path(td)
            ledger = self._ledger(base, [_make_receipt("a1")])
            out = base / "out"
            out.mkdir()
            (out / "existing").write_text("x")
            old = os.getcwd()
            try:
                os.chdir(td)
                # Non-empty output dir without --overwrite => write error => 1.
                rc = cli.main(
                    [
                        "--release-bundle",
                        "out",
                        "--receipts",
                        ledger,
                        "--policy",
                        "balanced",
                    ]
                )
                self.assertEqual(rc, 1)
                # With --overwrite it succeeds.
                rc2 = cli.main(
                    [
                        "--release-bundle",
                        "out",
                        "--receipts",
                        ledger,
                        "--policy",
                        "balanced",
                        "--overwrite",
                    ]
                )
                self.assertEqual(rc2, 0)
            finally:
                os.chdir(old)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
